spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/resident
    username: postgres
    password: postgres
  jpa:
    hibernate.ddl-auto: create-drop # create db when server starts, drop after
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
server:
  error:
    include-message: always # for malformed/bad requests

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /